# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"

# Oh My ZSH plugins
plugins=(git)

# Oh My ZSH
source $ZSH/oh-my-zsh.sh

if [[ -d "$HOME/.local/bin" ]]; then
  PATH="$PATH:$HOME/.local/bin"
fi

# Source local configs
LOCAL_ZSHRC="$HOME/.zshrc.local"
if [[ -d "$LOCAL_ZSHRC" ]]; then
  for rc_file in $LOCAL_ZSHRC/*; do
    echo "$HR Sourcing $rc_file";
    source "$rc_file";
  done
fi